flyway.url=jdbc:sqlserver://192.168.10.100:1433;databaseName=WPS_TEST3;encrypt=true;trustServerCertificate=true
flyway.user=sa
flyway.password=Utama1234

flyway.schemas=dbo
flyway.table=flyway_schema_history
flyway.locations=filesystem:db/migrations/sql

flyway.loggers=console

flyway.baselineOnMigrate=true
flyway.baselineVersion=0
flyway.baselineDescription=baseline existing schema
