name: Deploy to Server

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: self-hosted
    env:
      APP_DIR: /opt/wps_backend
    steps:
      - name: Pull latest code
        shell: bash
        run: git pull origin production
        working-directory: ${{ env.APP_DIR }}

      - name: Deploy with Docker
        shell: bash
        run: docker compose up -d --build
        working-directory: ${{ env.APP_DIR }}
