name: Deploy to Server

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: self-hosted

    env:
      APP_DIR: /opt/wps_backend

    steps:
      - name: Pull latest code
        shell: bash
        working-directory: ${{ env.APP_DIR }}
        run: git pull origin production

      - name: Deploy with Docker
        shell: bash
        working-directory: ${{ env.APP_DIR }}
        run: docker compose up -d --build

      - name: Cleanup Docker Images
        shell: bash
        run: docker image prune -f
